# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 80, host: 3000

  config.vm.synced_folder "../project", "/var/www/html/project", :mount_options => ['dmode=777', 'fmode=777']

  config.vm.provision :shell, path: "script/1_bootstrap.sh"
  config.vm.provision :shell, path: "script/2_install_lamp.sh"
  config.vm.provision :shell, path: "script/3_prep_cakephp.sh"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "shell", inline: "/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024", run: "always"
  config.vm.provision "shell", inline: "/sbin/mkswap /var/swap.1", run: "always"
  config.vm.provision "shell", inline: "/sbin/swapon /var/swap.1", run: "always"

end
